name: Codeception Tests

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.3, 8.4 ]
        wp: [ null, WordPress/WordPress#master ]
        include:
          - php: 8.4
            wp: WordPress/WordPress#6.6
          - php: 8.3
            wp: WordPress/WordPress#6.7
          - php: 8.3
            wp: WordPress/WordPress#6.6
          - php: 8.4
            wp: WordPress/WordPress#6.7

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer run-script packages-install
          npm ci
          docker run -d --shm-size="2g" --net=host --name="selenium-chromium" selenium/standalone-chromium:latest

      - name: Prepare testing environment variables
        run: |
          cp ./tests/.dist.env ./tests/.env

      - name: Override wp-env configuration
        run: |
          echo "{\"core\": \"${{ matrix.wp }}\", \"phpVersion\": \"${{ matrix.php }}\", \"env\": { \"development\": { \"plugins\": [] } } }" > .wp-env.override.json

      - name: Start wp-env
        run: npm run wp-env:start

      - name: Create database fixture
        run: npm run tests:export-db

      - name: Run tests
        run: npm run tests:run
